security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\EventAuthenticator
            logout:
                path: user_logout
                target: user_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /


    access_control:
         - { path: ^/login, roles: PUBLIC_ACCESS }
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/profile, roles: ROLE_USER }
         - { path: ^/user, roles: ROLE_USER }
         - { path: ^/user/create, roles: ROLE_USER }
         - { path: ^/user/update, roles: ROLE_USER }
         - { path: '^/user/delete/\d+$', roles: ROLE_ADMIN }
         - { path: '^/user/update/\d+$', roles: ROLE_ADMIN }
         - { path: '^/user/details/\d+$', roles: ROLE_USER }
         - { path: '^/user/registrationsList/\d+$', roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
